name: modul3prak
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  firebase_core : ^2.15.1
  firebase_auth : ^4.7.3
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  firebase_messaging : ^14.7.5 
  webview_flutter: ^4.2.2
  get: 4.6.6
  flutter:
    sdk: flutter
  firebase_in_app_messaging: ^0.7.4+5
  appwrite: ^11.0.0
  image_picker : ^0.8.4


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
