// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihOr38A09xKG5QP9dMlls7LVBHCMy5us',
    appId: '1:172332734559:web:1cc0e4d8c8d0dcc6e023ea',
    messagingSenderId: '172332734559',
    projectId: 'testfire-e44c9',
    authDomain: 'testfire-e44c9.firebaseapp.com',
    storageBucket: 'testfire-e44c9.appspot.com',
    measurementId: 'G-M6EJH0PPE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJI7E8GQ5iF7rn-mYFiM-3SsA_ckP1BbM',
    appId: '1:172332734559:android:7a5094a2d61b22f5e023ea',
    messagingSenderId: '172332734559',
    projectId: 'testfire-e44c9',
    storageBucket: 'testfire-e44c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxCN4_rgl6rBRiYyWKL5PbdA5zUU-wFfs',
    appId: '1:172332734559:ios:ef034c840659d4cbe023ea',
    messagingSenderId: '172332734559',
    projectId: 'testfire-e44c9',
    storageBucket: 'testfire-e44c9.appspot.com',
    iosBundleId: 'com.example.modul3prak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxCN4_rgl6rBRiYyWKL5PbdA5zUU-wFfs',
    appId: '1:172332734559:ios:aaff1d0f6daf70e8e023ea',
    messagingSenderId: '172332734559',
    projectId: 'testfire-e44c9',
    storageBucket: 'testfire-e44c9.appspot.com',
    iosBundleId: 'com.example.modul3prak.RunnerTests',
  );
}
